base:
  is_dev: false
out_dir: ./chdb  # 输出目录
url_tag: json # web url tag(json,db(https://github.com/google/go-querystring))
language: English # 语言(English,中 文)
db_tag: gorm # 数据库标签名(gorm,db)
simple: false # 简单输出(默认只输出gorm主键和字段标签)
user_gorm_model: false # model是否使用gorm.Model
is_db_tag: false # 是否输出 数据库标签(gorm,db)
is_out_sql: false # 是否输出 sql 原信息
is_out_func: false # 是否输出 快捷函数
is_web_tag: false # 是否打web标记(json标记前提条件)
is_web_tag_pk_hidden: false # web标记是否隐藏主键
is_foreign_key: false # 是否导出外键关联
is_gui: false # 是否ui模式显示
is_table_name: true # 是否直接生成表名
is_column_name: false # 是否直接生成列名
is_null_to_point: false # 数据库默认 'DEFAULT NULL' 时设置结构为指针类型
is_null_to_sql_null: false # 数据库默认 'DEFAULT NULL' 时设置结构为sql.NULL  is_null_to_point如果为true，则is_null_to_sql_null不生效
table_prefix: "" # 表前缀, 如果有则使用, 没有留空(如果表前缀以"-"开头，则表示去掉该前缀，struct、文件名都会去掉该前缀)
table_names: "" # 指定表生成，多个表用,隔开
is_out_file_by_table_name: true # 是否根据表名生成多个model
is_out_page: false # 是否输出分页函数

#db_info:
#  host: 47.111.102.169 # type=1的时候，host为yml文件全路径
#  port: 3306
#  username: buffalo
#  password: Buffalo$123
#  database: epro
#  type: 0 # 数据库类型:0:mysql , 1:sqlite , 2:mssql
db_info:
  host: 192.168.100.149 # type=1的时候，host为yml文件全路径
  port: 3306
  username: root
  password: ningyulin
  database: followup
  type: 0 # 数据库类型:0:mysql , 1:sqlite , 2:mssql
self_type_define: # 自定义数据类型映射
  datetime: "*time.Time"
#  datetime(3): "gorm.DeletedAt"
  time: "*time.Time"
  date: "*time.Time"
#  varchar: "sql.NullString"
#  varbinary: "sql.NullString"
#  text: "sql.NullString"
#  longtext: "sql.NullString"
#  json: "sql.NullString"
  ^(int)[(]\d+[)]: int32
out_file_name: "" # 自定义生成文件名
web_tag_type: 0 # json tag类型 0: 小驼峰 1: 下划线

# sqlite
# db_info:
#     host : /Users/xxj/Downloads/caoguo # type=1的时候，host为yml文件全路径
#     port :
#     username :
#     password :
#     database :
#     type: 1 # 数据库类型:0:mysql , 1:sqlite , 2:mssql