// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: patient.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PatientClient is the client API for Patient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatientClient interface {
	// 添加患者
	PatientCreate(ctx context.Context, in *PatientCreateRequest, opts ...grpc.CallOption) (*PatientCreateResponse, error)
	// 删除患者
	PatientDelete(ctx context.Context, in *PatientDeleteRequest, opts ...grpc.CallOption) (*PatientDeleteResponse, error)
	// 更新患者信息
	PatientUpdate(ctx context.Context, in *PatientUpdateRequest, opts ...grpc.CallOption) (*PatientUpdateResponse, error)
	// 患者详情查询
	PatientDetail(ctx context.Context, in *PatientDetailRequest, opts ...grpc.CallOption) (*PatientDetailResponse, error)
	// 患者过滤查询
	PatientFilter(ctx context.Context, in *PatientFilterRequest, opts ...grpc.CallOption) (*PatientFilterResponse, error)
}

type patientClient struct {
	cc grpc.ClientConnInterface
}

func NewPatientClient(cc grpc.ClientConnInterface) PatientClient {
	return &patientClient{cc}
}

func (c *patientClient) PatientCreate(ctx context.Context, in *PatientCreateRequest, opts ...grpc.CallOption) (*PatientCreateResponse, error) {
	out := new(PatientCreateResponse)
	err := c.cc.Invoke(ctx, "/api.Patient/PatientCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientClient) PatientDelete(ctx context.Context, in *PatientDeleteRequest, opts ...grpc.CallOption) (*PatientDeleteResponse, error) {
	out := new(PatientDeleteResponse)
	err := c.cc.Invoke(ctx, "/api.Patient/PatientDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientClient) PatientUpdate(ctx context.Context, in *PatientUpdateRequest, opts ...grpc.CallOption) (*PatientUpdateResponse, error) {
	out := new(PatientUpdateResponse)
	err := c.cc.Invoke(ctx, "/api.Patient/PatientUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientClient) PatientDetail(ctx context.Context, in *PatientDetailRequest, opts ...grpc.CallOption) (*PatientDetailResponse, error) {
	out := new(PatientDetailResponse)
	err := c.cc.Invoke(ctx, "/api.Patient/PatientDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientClient) PatientFilter(ctx context.Context, in *PatientFilterRequest, opts ...grpc.CallOption) (*PatientFilterResponse, error) {
	out := new(PatientFilterResponse)
	err := c.cc.Invoke(ctx, "/api.Patient/PatientFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatientServer is the server API for Patient service.
// All implementations must embed UnimplementedPatientServer
// for forward compatibility
type PatientServer interface {
	// 添加患者
	PatientCreate(context.Context, *PatientCreateRequest) (*PatientCreateResponse, error)
	// 删除患者
	PatientDelete(context.Context, *PatientDeleteRequest) (*PatientDeleteResponse, error)
	// 更新患者信息
	PatientUpdate(context.Context, *PatientUpdateRequest) (*PatientUpdateResponse, error)
	// 患者详情查询
	PatientDetail(context.Context, *PatientDetailRequest) (*PatientDetailResponse, error)
	// 患者过滤查询
	PatientFilter(context.Context, *PatientFilterRequest) (*PatientFilterResponse, error)
	mustEmbedUnimplementedPatientServer()
}

// UnimplementedPatientServer must be embedded to have forward compatible implementations.
type UnimplementedPatientServer struct {
}

func (UnimplementedPatientServer) PatientCreate(context.Context, *PatientCreateRequest) (*PatientCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientCreate not implemented")
}
func (UnimplementedPatientServer) PatientDelete(context.Context, *PatientDeleteRequest) (*PatientDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientDelete not implemented")
}
func (UnimplementedPatientServer) PatientUpdate(context.Context, *PatientUpdateRequest) (*PatientUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientUpdate not implemented")
}
func (UnimplementedPatientServer) PatientDetail(context.Context, *PatientDetailRequest) (*PatientDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientDetail not implemented")
}
func (UnimplementedPatientServer) PatientFilter(context.Context, *PatientFilterRequest) (*PatientFilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientFilter not implemented")
}
func (UnimplementedPatientServer) mustEmbedUnimplementedPatientServer() {}

// UnsafePatientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatientServer will
// result in compilation errors.
type UnsafePatientServer interface {
	mustEmbedUnimplementedPatientServer()
}

func RegisterPatientServer(s grpc.ServiceRegistrar, srv PatientServer) {
	s.RegisterService(&Patient_ServiceDesc, srv)
}

func _Patient_PatientCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).PatientCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Patient/PatientCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).PatientCreate(ctx, req.(*PatientCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Patient_PatientDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).PatientDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Patient/PatientDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).PatientDelete(ctx, req.(*PatientDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Patient_PatientUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).PatientUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Patient/PatientUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).PatientUpdate(ctx, req.(*PatientUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Patient_PatientDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).PatientDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Patient/PatientDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).PatientDetail(ctx, req.(*PatientDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Patient_PatientFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).PatientFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Patient/PatientFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).PatientFilter(ctx, req.(*PatientFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Patient_ServiceDesc is the grpc.ServiceDesc for Patient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Patient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Patient",
	HandlerType: (*PatientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PatientCreate",
			Handler:    _Patient_PatientCreate_Handler,
		},
		{
			MethodName: "PatientDelete",
			Handler:    _Patient_PatientDelete_Handler,
		},
		{
			MethodName: "PatientUpdate",
			Handler:    _Patient_PatientUpdate_Handler,
		},
		{
			MethodName: "PatientDetail",
			Handler:    _Patient_PatientDetail_Handler,
		},
		{
			MethodName: "PatientFilter",
			Handler:    _Patient_PatientFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "patient.proto",
}
